#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [ -n "$TMUX" ]; then
    export TERM="screen-256color"
elif ! `tty|grep -q "tty"`; then
    export TERM="xterm-256color"
else
    export TERM="linux"
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
export VBOX_LOG_DEST=nofile
export PYTHONSTARTUP=~/.pythonrc
export PATH=$HOME/bin:$PATH


unset MAILCHECK
export QMAKE=/usr/lib/qt4/bin/qmake

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

